# Generated by Django 5.0.6 on 2024-06-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_genre_options_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
