# Generated by Django 5.0.6 on 2024-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('AZ', 'Az dili'), ('RU', 'RU'), ('EN', 'EN')], max_length=2, null=True),
        ),
    ]
