# Generated by Django 5.0.6 on 2024-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('AZ', 'Az'), ('RU', 'RU'), ('EN', 'EN')], max_length=2, null=True),
        ),
    ]
