# Generated by Django 5.0.6 on 2024-06-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookphoto_options_alter_bookphoto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookphoto',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='books.book'),
        ),
    ]
